[feat](ramdisk):ramdisk for bm1688 v1.5 [description ]:NA [root   cause]:NA [JIRA      ID]:NA [chip project]:NA [side effects]:NA [Affected *.ko/*.so/*.a] :NA

diff --git a/rootfs/overlay/bm1688/etc/init.d/S28utelnetd b/rootfs/overlay/bm1688/etc/init.d/S28utelnetd
--- a/rootfs/overlay/bm1688/etc/init.d/S28utelnetd
+++ b/rootfs/overlay/bm1688/etc/init.d/S28utelnetd
@@ -5,8 +5,12 @@
 #
 
 if [ -f /usr/bin/utelnetd ];then
-	printf "Starting utelnetd:"
-	start-stop-daemon -S -q -b -x /usr/bin/utelnetd -- -p 23 -d
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	case "$1" in
+		start)
+			printf "Starting utelnetd:"
+			start-stop-daemon -S -q -b -x /usr/bin/utelnetd -- -p 23 -d
+			[ $? = 0 ] && echo "OK" || echo "FAIL"
+			;;
+	esac
 fi
 exit 0
