ramdisk: weekly rls 2024.09.21
    -43832b9, [feat](usb): fix UDC & add depend ko.
    -d58e66a, Merge "[fix](bin):change cvi_pinmux and logrotate to arm64."
    -244f66c, [fix](fastboot):Add mktemp tools.

diff --git a/rootfs/common_musl_riscv64/etc/init.d/S01syslogd b/rootfs/common_musl_riscv64/etc/init.d/S01syslogd
--- a/rootfs/common_musl_riscv64/etc/init.d/S01syslogd
+++ b/rootfs/common_musl_riscv64/etc/init.d/S01syslogd
@@ -26,15 +26,20 @@ start() {
 
 stop() {
 	printf 'Stopping %s: ' "$DAEMON"
-	start-stop-daemon -K -q -p "$PIDFILE"
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		rm -f "$PIDFILE"
-		echo "OK"
-	else
-		echo "FAIL"
+	if [ -f "$PIDFILE" ]; then
+		pid=$(cat "$PIDFILE")
+		if kill -0 "$pid" 2>/dev/null; then
+			start-stop-daemon -K -q -p "$PIDFILE"
+			status=$?
+			if [ "$status" -eq 0 ]; then
+				rm -f "$PIDFILE"
+				echo "OK"
+			else
+				echo "FAIL"
+			fi
+			return "$status"
+		fi
 	fi
-	return "$status"
 }
 
 restart() {
